name: "Docs: Build and Commit to LS"

on:
  workflow_call:
  workflow_dispatch:

env:
  LSF_DIR: 'label-studio-frontend'
  TARGET_REPO: 'heartexlabs/label-studio'
  LS_DIR: 'label-studio'
  NODE: '18'
  CACHE_NAME_PREFIX: v1

jobs:
  build-and-commit-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Checkout LSF
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 1
          path: ${{ env.LSF_DIR }}

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ env.CACHE_NAME_PREFIX }}-${{ runner.os }}-node-${{ env.NODE }}-jsdoc-to-markdown

      - name: Install NPM deps
        working-directory: ${{ env.LSF_DIR }}/scripts
        run: npm install jsdoc-to-markdown node-fetch

      - name: Build docs
        working-directory: ${{ env.LSF_DIR }}/scripts
        run: node create-docs.js

      - name: Get GitHub user details
        id: get-github-user
        uses: actions/github-script@v6
        env:
          ACTOR_USERNAME: ${{ github.event.sender.login }}
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const actor_username = process.env.ACTOR_USERNAME;
            
            let user_name = 'robot-ci-heartex';
            let user_email = 'robot-ci-heartex@users.noreply.github.com';
            
            try {
              const {data: user} = await github.rest.users.getByUsername({
                username: actor_username,
              });
              user_name = user.login;
              user_email = user.email;
            } catch (e) {
              console.log(e)
            }
            
            core.setOutput('user_name', user_name);
            core.setOutput('user_email', user_email);

      - name: Configure git
        shell: bash
        run: |
          set -xeuo pipefail
          git config --global user.name '${{ steps.get-github-user.outputs.user_name }}'
          git config --global user.email '${{ steps.get-github-user.outputs.user_email }}'

      - name: Checkout LS
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 1
          repository: ${{ env.TARGET_REPO }}
          path: ${{ env.LS_DIR }}

      - name: Commit docs
        working-directory: ${{ env.LS_DIR }}
        run: |
          cp -Rf ${GITHUB_WORKSPACE}/${{ env.LSF_DIR }}/docs/* ${GITHUB_WORKSPACE}/${{ env.LS_DIR }}/docs/source/tags/
          git status
          git add .
          git commit -m 'docs: LSF Update'
          git push origin
