name: "Send tests coverage"

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string

jobs:
  run_unit_coverage_upload:
    name: "Upload unit coverage"
    runs-on: ubuntu-latest

    # ci can be skipped with `[skip ci]` prefix in message
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: "Checkout codebase"
        uses: actions/checkout@v4

      - name: "Download Unit coverage from Artifact"
        uses: ./.github/actions/download-artifact
        with:
          name: unit-tests-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.1.1
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          fail_ci_if_error: true
          token: ${{ secrets.codecov_token }}

  run_e2e_coverage_upload:
    name: Upload E2E coverage
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: "Checkout codebase"
        uses: actions/checkout@v4

      - name: "Download E2E coverage from Artifact"
        uses: ./.github/actions/download-artifact
        with:
          name: e2e-tests-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.1.1
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          fail_ci_if_error: true
          token: ${{ secrets.codecov_token }}

  run_cypress_coverage_upload:
    name: Upload Cypress coverage
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: "Checkout codebase"
        uses: actions/checkout@v4

      - name: "Download Cypress coverage from Artifact"
        uses: ./.github/actions/download-artifact
        with:
          name: cypress-tests-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.1.1
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          fail_ci_if_error: true
          token: ${{ secrets.codecov_token }}
